# Key codes to generate the graph were provided, and data were stored in Data obj

tab = read.csv(file = 'Result/ARG_MGE/reNew/Odds Ratio (CRC vs. CTRL).all.csv')
  
  ggplot(tab, aes(x=ID, y=OR.estimate)) + 
    geom_hline(yintercept = 1, col = 'grey', lwd = 1, lty = 'dotted') +
    geom_errorbar(aes(ymin=OR.lower, ymax=OR.upper), width=.2, position=position_dodge(0.4))+
    geom_point(shape = 18, col = 'red', position=position_dodge(0.4), size = 4, alpha = 1) +
    # geom_vline(xintercept = 0, col = 'black', lwd = 1.5) +
    theme_minimal() + 
    labs(x = '', y = 'log 10 OR (CRC / CTRL; P<0.1)') +
    theme(#panel.border = element_rect(colour = 'black', fill = NA, linewidth = 1),
      panel.grid = element_line(color = 'white', linetype = 1), 
      panel.background = element_rect(fill = 'white', colour = 'white'),
      legend.position = 'none', #, c(1.0, 1.0), 
      legend.spacing.x = unit(x = 6, units = 'pt'),
      legend.title = element_blank(),
      legend.text = element_text(size = 8),
      legend.key.size = unit(x = 8, units = 'pt'),
      legend.background = element_rect(fill="white", size=.5, linetype="solid", colour = 'black'), 
      axis.title = element_text(size = 11, color = 'black'), 
      axis.text.x = element_text(size = 10, color = 'black'), # , angle = 90, vjust = 1, hjust = 1
      axis.text.y = element_text(size = 10, color = 'black'),
      axis.line.x = element_line(colour = 'black'),
      axis.ticks.x.bottom = element_blank(),
      # axis.ticks.y.left = element_line(colour = 'black'),
      axis.ticks.length = unit(.1, "cm")) +
    # scale_y_continuous(limits = c(0, 10), breaks = c(0, 1, 5, 10), expand = expansion(add = 0)) + 
    # scale_y_continuous(trans = ggallin::ssqrt_trans, expand = expansion(mult = c(0, 0.1))) +
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                  label = scales::trans_format("log10", scales::math_format(.x)),
                  expand = expansion(mult = c(0, 0.01))) +
    annotation_logticks(sides = 'b', size = 0.4,
                        short = unit(0.05, "cm"),
                        mid = unit(0.1, "cm"),
                        long = unit(0.2, "cm")) +
    coord_flip()
