# updating
## - code for calculating core index
  tab = do.call('rbind', lapply(rownames(dat_used), function(x) {
    # x = as.numeric(dat_used[120, ])
    xx = as.numeric(dat_used[x, ]); names(xx) = colnames(dat_used)
    tab = cbind(pheno[, c("Cohort", "Stage")], 
                Cohort_Stage = paste(pheno$Cohort, pheno$Stage, sep = '.'), 
                val = xx[rownames(pheno)])
    yy = sapply(unique(tab$Cohort), function(cht) {
      t1 = tab[tab$Cohort == cht, ]
      y = c(ai = sum(t1$Stage == 'CRC' & t1$val > 0), n1i = sum(t1$Stage == 'CRC'),
            ci = sum(t1$Stage == 'CTRL' & t1$val > 0), n2i = sum(t1$Stage == 'CTRL'))
      res = fisher.test(matrix(c(y['ai'], y['n1i']-y['ai'], y['ci'], y['n2i']-y['ci']), nrow = 2))
      c(y, freq = y['ai'] / y['n1i'], freq = y['ci'] / y['n2i'],
        res$estimate, p.val = res$p.value)
    })
    yy = as.data.frame(t(yy))
    
    y1 = c(CRC.w = sum(yy$freq.ai > 0.5) / dim(yy)[1], 
           CTRL.w = sum(yy$freq.ci > 0.5) / dim(yy)[1])
    
    y2 = c(CRC = unlist(predict(rma(measure="PLO", xi=ai, ni=n1i, data=yy, control=list(stepadj=0.5, maxiter=1000)), transf=transf.ilogit))[c('pred')],
           CTRL = unlist(predict(rma(measure="PLO", xi=ci, ni=n2i, data=yy, control=list(stepadj=0.5, maxiter=1000)), transf=transf.ilogit))[c('pred')])
    y2 = as.numeric(y2); names(y2) = c('CRC.pred', 'CTRL.pred')
    
    y = c(y1, y2, 
          CRC.avg = mean(as.numeric(dat_used.rel[x, which(pheno$Stage == 'CRC')])),
          CTRL.avg = mean(as.numeric(dat_used.rel[x, which(pheno$Stage == 'CTRL')])))
    c(y, 
      CRC.CI = unname(y['CRC.w'] * y['CRC.pred'] * y['CRC.avg']),
      CTRL.CI = unname(y['CTRL.w'] * y['CTRL.pred'] * y['CTRL.avg']))
  }) )
  tab = as.data.frame(tab, stringsAsFactors = FALSE)
  rownames(tab) = rownames(dat_used)
  
  ### - draw density, fit normal dist
  tab$diff = tab$CRC.CI - tab$CTRL.CI
  tab.noZero = tab[tab$diff != 0, ]
  
  qu = qnorm(0.975, mean = mean(tab.noZero$diff), sd = sd(tab.noZero$diff)/sqrt(dim(tab.noZero)[1]))
  ql = qnorm(0.025, mean = mean(tab.noZero$diff), sd = sd(tab.noZero$diff)/sqrt(dim(tab.noZero)[1]))
  tab.noZero$`p<0.05` = sapply(tab.noZero$diff, function(x) {
    if (x > 0) return(x > qu) else return(x < ql)
  })
  
  ## -
  tps_col = Data$tps_col
  
  g <- ggplot(data = Data$CI_diff.stool, mapping = aes(x = ID, y = value, fill = type)) + 
    geom_hline(yintercept = 0, color = 'black', lwd = 0.3) +
    geom_bar(stat="identity", position=position_dodge(0.4),
             width = 0.1, alpha = 1, lwd = 0.1, color = 'grey', fill = 'grey')+
    geom_point(shape = 21, col = 'black', position=position_dodge(0.4), size = 2, alpha = 1) +
    geom_hline(yintercept = 0) +
    labs(x = '', y = 'CI diff')
  g <- g + theme_minimal() + 
    theme(panel.grid = element_line(color = 'white', linetype = 1), 
          legend.position = 'none', #, c(1.0, 1.0), 
          legend.spacing.x = unit(x = 6, units = 'pt'),
          legend.title = element_blank(),
          legend.text = element_text(size = 8),
          legend.key.size = unit(x = 8, units = 'pt'),
          legend.background = element_rect(fill="white", size=.5, linetype="solid", colour = 'black'), 
          axis.line.x.bottom = element_line(colour = 'black', linewidth = 0.8),
          axis.ticks.length.x.bottom = unit(0.1, "cm"),
          axis.ticks.x.bottom = element_line(colour = 'black', linewidth = 0.8),
          axis.title = element_text(size = 12), 
          axis.text.x = element_text(size = 9, color = 'black', angle = 60, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 8, color = 'black'))
  g <- g +
    scale_fill_manual(values = tps_col) +
    scale_y_continuous(trans = ggallin::ssqrt_trans, expansion(mult = c(0.1, 0.3)), limits = c(-.009, .005)) +
    annotation_logticks(sides = 'b', size = 0.4,
                        short = unit(0.1, "cm"),
                        mid = unit(0.2, "cm"),
                        long = unit(0.3, "cm"))
  g + coord_flip()
  
  ## -
  g <- ggplot(data = Data$CI.env, mapping = aes(x = ID, y = value)) + 
    geom_hline(yintercept = 0, color = 'black', lwd = 0.3, lty = 'dashed') +
    geom_errorbar(aes(ymin=value-sd, ymax=value+sd), width=.0, position=position_dodge(0.4)) +
    geom_point(aes(shape = group), fill = 'black', col = 'black', position=position_dodge(0.4), size = 2, alpha = 1) +
    labs(x = '', y = 'Core index') + 
    theme_minimal() + 
    theme(panel.grid = element_line(color = 'white', linetype = 1), 
          legend.position = 'none', #, c(1.0, 1.0), 
          legend.spacing.x = unit(x = 6, units = 'pt'),
          legend.title = element_blank(),
          legend.text = element_text(size = 8),
          legend.key.size = unit(x = 8, units = 'pt'),
          legend.background = element_rect(fill="white", size=.5, linetype="solid", colour = 'black'), 
          axis.line.x.bottom = element_line(colour = 'black', linewidth = 0.5),
          axis.line.y.left = element_blank(), # element_line(colour = 'black', linewidth = 0.5),
          axis.ticks.length.y.left = unit(0.1, "cm"),
          axis.ticks.y.left = element_blank(), #element_line(colour = 'black', linewidth = 0.8),
          axis.title = element_text(size = 12), 
          axis.text.x = element_text(size = 9, color = 'black', angle = 60, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 8, color = 'black'))
  g <- g +
    scale_shape_manual(values = c('FALSE'=22, 'TRUE'=23)) +
    scale_y_continuous(trans = ggallin::ssqrt_trans, expand = expansion(mult = c(0, 0.1))) +
    annotation_logticks(sides = 'b', size = 0.4,
                        short = unit(0.05, "cm"),
                        mid = unit(0.1, "cm"),
                        long = unit(0.2, "cm"))
  # g
  g + coord_flip()
